<?PHP
$productos = [
    'zapatillas' => [
        [
            'id' => 1,
            'nombre' => 'Trip Premium',
            'marca' => 'Spiral',
            'tipo' => 'Zapatillas Urbanas',
            'color' => 'Negro',
            'talles' => ['40', '41', '42', '43', '44'],
            'img' => 'zapatillas/trip-premium.jpg',
            'descripcion' => 'Estamos emocionados de presentar el modelo TRIP, la zapatilla que combina la robustez del calzado skater profesional con un estilo chunky de última tendencia. Diseñada para ofrecer el máximo confort y durabilidad, la TRIP presenta cordones Spiral Laces Chunky y un relleno de espuma de alta densidad de 20 mm, que garantizan un ajuste superior y comodidad sin igual.',
            'temporada' => 'Invierno, 2024',
            'precio' => 92819
        ],
        [
            'id' => 2,
            'nombre' => 'G.O.A.T High',
            'marca' => 'Spiral',
            'tipo' => 'Botas',
            'color' => 'Blanco',
            'talles' => ['38', '39', '40', '41', '42'],
            'img' => 'zapatillas/goat-high-white.jpg',
            'descripcion' => 'GOAT HIGH se destaca por su altura sobre el tobillo y un elegante cierre de velcro que proporciona tanto estilo como sujeción. La zapatilla incorpora una espuma de poliuretano de alta densidad y refuerzos internos en Goma EVA, diseñados para ofrecer una protección superior contra golpes e impactos durante la práctica del skate. La suela de goma de alta resistencia a la abrasión garantiza una tracción duradera, mientras que la capellada está confeccionada en cuero vacuno natural.',
            'temporada' => 'Invierno, 2024',
            'precio' => 109199
        ],
        [
            'id' => 3,
            'nombre' => 'Court Graffik Ss (wlk)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Blanca',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/court-graffik-wlk.jpg',
            'descripcion' => 'La Court Graffik sigue mejorando con el tiempo, su clásica silueta hinchada siempre está evolucionando con colores de moda, llamativos logotipos de DC y nuevas telas que se destacan entre la multitud. Capellada de PU Sintético + Forrería liviana de lengüeta + Cuello y lengüeta con espuma acolchada para máximo confort y soporte + Perforaciones de ventilación para una mejor respirabilidad del pie + Suela Cupsole de caucho resistente a la abrasión con costura alrededor, proveyendo mayor durabilidad y resistencia + Diseño Pill Pattern de DC en pisada',
            'temporada' => 'Verano, 2024',
            'precio' => 144990
        ],
        [
            'id' => 4,
            'nombre' => 'Court Graffik Ss (Xw)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas urbana',
            'color' => 'Blanca',
            'talles' => ['4', '5', '6', '7', '8'],
            'img' => 'zapatillas/court-graffik-xw.jpg',
            'descripcion' => 'La Court Graffik sigue mejorando con el tiempo, su clásica silueta hinchada siempre está evolucionando con colores de moda, llamativos logotipos de DC y nuevas telas que se destacan entre la multitud. Capellada de PU Sintético + Forrería liviana de lengüeta + Cuello y lengüeta con espuma acolchada para máximo confort y soporte + Perforaciones de ventilación para una mejor respirabilidad del pie + Suela Cupsole de caucho resistente a la abrasión con costura alrededor, proveyendo mayor durabilidad y resistencia + Diseño Pill Pattern de DC en pisada',
            'temporada' => 'Verano, 2024',
            'precio' => 144990
        ],
        [
            'id' => 5,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
    ],
    'hombre' => [
        [
            'id' => 6,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 7,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 8,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 9,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 10,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
    ],
    'mujer' => [
        [
            'id' => 11,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 12,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 13,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 14,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 15,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
    ],
    'accesorios' => [
        [
            'id' => 16,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 17,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 18,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 19,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
        [
            'id' => 20,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
    ],
];