<?PHP
$productos = [
    'zapatillas' => [
        [
            'id' => 1,
            'nombre' => 'Trip Premium',
            'marca' => 'Spiral',
            'tipo' => 'Zapatillas Urbanas',
            'color' => 'Negro',
            'talles' => ['40', '41', '42', '43', '44'],
            'img' => 'zapatillas/trip-premium.jpg',
            'descripcion' => 'Estamos emocionados de presentar el modelo TRIP, la zapatilla que combina la robustez del calzado skater profesional con un estilo chunky de última tendencia. Diseñada para ofrecer el máximo confort y durabilidad, la TRIP presenta cordones Spiral Laces Chunky y un relleno de espuma de alta densidad de 20 mm, que garantizan un ajuste superior y comodidad sin igual.',
            'temporada' => 'Invierno, 2024',
            'precio' => 92819
        ],
        [
            'id' => 2,
            'nombre' => 'G.O.A.T High',
            'marca' => 'Spiral',
            'tipo' => 'Botas',
            'color' => 'Blanco',
            'talles' => ['38', '39', '40', '41', '42'],
            'img' => 'zapatillas/goat-high-white.jpg',
            'descripcion' => 'GOAT HIGH se destaca por su altura sobre el tobillo y un elegante cierre de velcro que proporciona tanto estilo como sujeción. La zapatilla incorpora una espuma de poliuretano de alta densidad y refuerzos internos en Goma EVA, diseñados para ofrecer una protección superior contra golpes e impactos durante la práctica del skate. La suela de goma de alta resistencia a la abrasión garantiza una tracción duradera, mientras que la capellada está confeccionada en cuero vacuno natural.',
            'temporada' => 'Invierno, 2024',
            'precio' => 109199
        ],
        [
            'id' => 3,
            'nombre' => 'Court Graffik Ss (wlk)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Blanca',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/court-graffik-wlk.jpg',
            'descripcion' => 'La Court Graffik sigue mejorando con el tiempo, su clásica silueta hinchada siempre está evolucionando con colores de moda, llamativos logotipos de DC y nuevas telas que se destacan entre la multitud. Capellada de PU Sintético + Forrería liviana de lengüeta + Cuello y lengüeta con espuma acolchada para máximo confort y soporte + Perforaciones de ventilación para una mejor respirabilidad del pie + Suela Cupsole de caucho resistente a la abrasión con costura alrededor, proveyendo mayor durabilidad y resistencia + Diseño Pill Pattern de DC en pisada',
            'temporada' => 'Verano, 2024',
            'precio' => 144990
        ],
        [
            'id' => 4,
            'nombre' => 'Court Graffik Ss (Xw)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas urbana',
            'color' => 'Blanca',
            'talles' => ['4', '5', '6', '7', '8'],
            'img' => 'zapatillas/court-graffik-xw.jpg',
            'descripcion' => 'La Court Graffik sigue mejorando con el tiempo, su clásica silueta hinchada siempre está evolucionando con colores de moda, llamativos logotipos de DC y nuevas telas que se destacan entre la multitud. Capellada de PU Sintético + Forrería liviana de lengüeta + Cuello y lengüeta con espuma acolchada para máximo confort y soporte + Perforaciones de ventilación para una mejor respirabilidad del pie + Suela Cupsole de caucho resistente a la abrasión con costura alrededor, proveyendo mayor durabilidad y resistencia + Diseño Pill Pattern de DC en pisada',
            'temporada' => 'Verano, 2024',
            'precio' => 144990
        ],
        [
            'id' => 5,
            'nombre' => 'Lynx Zero (Wdb)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Zapatillas Urbana',
            'color' => 'Gris',
            'talles' => ['8', '9', '10', '11', '12'],
            'img' => 'zapatillas/lynx-zero-gris.jpg',
            'descripcion' => 'Capellada de Cuero, Nobuck, descarne o Mesh + Logo lateral de DC modeado en TPR + Cuello y lengüeta con espuma acolchada para proveer mayor confort + Forrería en mesh respirable + Plantilla interna en EVA + Pisada con diseño Pill Pattern de DC.',
            'temporada' => 'Invierno, 2024',
            'precio' => 159990
        ],
    ],

    'hombre' => [
        [
            'id' => 6,
            'nombre' => 'Static 94 (Neg)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Campera',
            'color' => 'Negro',
            'talles' => ['xs', 's', 'm', 'l', 'xl', 'xxl'],
            'img' => 'hombre/campera-dc-static.jpg',
            'descripcion' => 'TELA 100% Poliester Campera Tejido: Mini ripstop Fit: Boxy Estampa reflex en pecho y espalda Cordon en cintura Ventilacion en canesu central trasero Avios DC',
            'temporada' => 'Invierno, 2024',
            'precio' => 169990
        ],
        [
            'id' => 7,
            'nombre' => 'Chaleco Static 94',
            'marca' => 'Dc Shoes',
            'tipo' => 'Chaleco',
            'color' => 'Negro',
            'talles' => ['xs', 's', 'm', 'l', 'xl', 'xxl'],
            'img' => 'hombre/chaleco-dc-static.jpg',
            'descripcion' => 'TELA 100% Algodon Chaleco Tejido: Gabardina elastizada Fit: Boxy Estampa reflex en el frente Bolsillos con fuelles y- tapa Avios DC',
            'temporada' => 'Invierno, 2024',
            'precio' => 116990
        ],
        [
            'id' => 8,
            'nombre' => 'Canguro Biceps Orange',
            'marca' => 'Rusty',
            'tipo' => 'Buzo',
            'color' => 'Naranja',
            'talles' => ['xs', 's', 'm', 'l', 'xl', 'xxl'],
            'img' => 'hombre/buzo-rusty-orange.jpg',
            'descripcion' => 'Buzo manga corta-manga larga con capucha, bolsillo tipo canguro, con cintura y puños de ribb elastizado. Tejido: Frisa invisible. Composición: Algodón 88% - Poliéster 12% Tipo de calce: Relaxed fit. Artes: Estampados en serigrafía de plastisol.',
            'temporada' => 'Invierno, 2024',
            'precio' => 51990
        ],
        [
            'id' => 9,
            'nombre' => 'Campera Canguro Pure O2 Black',
            'marca' => 'Rusty',
            'tipo' => 'Campera',
            'color' => 'Negra',
            'talles' => ['xs', 's', 'm', 'l', 'xl', 'xxl'],
            'img' => 'hombre/campera-rusty-pure.jpg',
            'descripcion' => 'Campera con capucha, bolsillo tipo canguro, con cintura y puños de ribb elastizado. Tejido: Frisa invisible. Composición: Algodón 88% - Poliéster 12% Tipo de calce: Regular fit.',
            'temporada' => 'Invierno, 2024',
            'precio' => 59990
        ],
        [
            'id' => 10,
            'nombre' => 'Jean Dungaree Denim Ash Blue',
            'marca' => 'Rusty',
            'tipo' => 'Pantalon',
            'color' => 'Jean claro',
            'talles' => ['28', '30', '32', '34', '36','38'],
            'img' => 'hombre/pantalon-rusty-dungaree.jpg',
            'descripcion' => 'Este pantalón de jean estilo worker está confeccionado en denim índigo 100% algodón, diseñado para ofrecer durabilidad y comodidad con un calce relaxed fit. Cuenta con un lavado stone wash con enzimático, sin localizado, que le otorga un acabado robusto.',
            'temporada' => 'Invierno, 2024',
            'precio' => 104990
        ],
    ],
    'mujer' => [
        [
            'id' => 11,
            'nombre' => 'Shift Oversized',
            'marca' => 'Dc Shoes',
            'tipo' => 'Remera Mc',
            'color' => 'Negra',
            'talles' => ['xs', 's', 'm', 'l', 'xl'],
            'img' => 'mujer/shift-oversized.jpg',
            'descripcion' => 'TELA 100% Algodón Remera manga corta  Tejido: Jersey 24.1 Fit: Oversized Estampa en el frente Avios DC.',
            'temporada' => 'Verano, 2024',
            'precio' => 32990
        ],
        [
            'id' => 12,
            'nombre' => 'The Weekend New Fit (Vee)',
            'marca' => 'Dc Shoes',
            'tipo' => 'Remera Mc',
            'color' => 'Verde',
            'talles' => ['xs', 's', 'm', 'l', 'xl'],
            'img' => 'mujer/the-weekend.jpg',
            'descripcion' => 'La remera DC para mujer en color verde está confeccionada en 100% algodón de alta calidad, con tejido Jersey 30.1 que ofrece suavidad y comodidad. Presenta un diseño de manga corta y un corte New Fit que se ajusta perfectamente a la silueta femenina, ideal para un look casual y urbano',
            'temporada' => 'Verano, 2024',
            'precio' => 28990
        ],
        [
            'id' => 13,
            'nombre' => 'Billie Low Wide Canvas Carpenter Black',
            'marca' => 'Rusty',
            'tipo' => 'Pantalon',
            'color' => 'Negro',
            'talles' => ['24', '26', '28', '30', '32', '34'],
            'img' => 'mujer/billie-low.jpg',
            'descripcion' => 'Pantalón carpintero recto tiro bajo con detalles de presilla para martillo bordada. Bolsillos plaque delantero. Bolsillos plaque traseros con bordado logo a contratono. Tejido: lona tejida - 100% poliamida',
            'temporada' => 'Invierno, 2024',
            'precio' => 74990
        ],
        [
            'id' => 14,
            'nombre' => 'Jean Penny Black Slim Black',
            'marca' => 'Rusty',
            'tipo' => 'Pantalon',
            'color' => 'Negro',
            'talles' => ['24', '26', '28', '30', '32', '34'],
            'img' => 'mujer/penny-black.jpg',
            'descripcion' => 'Este jean slim fit de tiro medio está confeccionado en Stretch Denim, compuesto por 98% algodón y 2% elastano, ofreciendo una combinación ideal de comodidad y flexibilidad. Presenta un lavado enzimático super stone wash que le da un aspecto desgastado en color negro, con roturas comunes y tajos en la bota para un estilo moderno y urbano.',
            'temporada' => 'Invierno, 2024',
            'precio' => 94990
        ],
    ],
    'accesorios' => [
        [
            'id' => 15,
            'nombre' => 'Mochila Off Road* Black/Purple',
            'marca' => 'Rusty',
            'tipo' => 'Mochila',
            'color' => 'Negro/Violeta',
            'talles' => 'U',
            'img' => 'accesorios/mochila-rusty-road.jpg',
            'descripcion' => 'Esta mochila de viaje y outdoor, con capacidad de 22 litros, está diseñada para la aventura y la comodidad. Sus dimensiones de 44 cm de alto, 31 cm de ancho y 16 cm de profundidad la hacen ideal para llevar lo esencial. Fabricada en poliéster resistente con detalles en red de poliéster.',
            'temporada' => 'Invierno, 2024',
            'precio' => 74890
        ],
        [
            'id' => 16,
            'nombre' => 'Medias All Day Invisible 5- Pack',
            'marca' => 'Rusty',
            'tipo' => 'Medias Cortas',
            'color' => 'Mix',
            'talles' => 'U',
            'img' => 'accesorios/media-rusty-allday.jpg',
            'descripcion' => 'El pack de 5 medias All Day Invisible está diseñado para brindar comodidad y discreción en cualquier calzado. Fabricadas con materiales suaves y elásticos, estas medias invisibles se ajustan perfectamente al pie, proporcionando una sensación de ligereza durante todo el día.',
            'temporada' => 'Verano, 2024',
            'precio' => 27490
        ],
        [
            'id' => 17,
            'nombre' => 'Gorra Chronic 4 Flexfit',
            'marca' => 'Rusty',
            'tipo' => 'Gorra',
            'color' => 'Negro',
            'talles' => 'U',
            'img' => 'accesorios/gorra-rusty-chronic-negra.jpg',
            'descripcion' => 'Gorra de gabardina elastizada con visera semi curva y logo bordado en 3D El calce esta regulado por elástico con personalizado de marca.',
            'temporada' => 'Invierno, 2024',
            'precio' => 34890
        ],
        [
            'id' => 18,
            'nombre' => 'Morral Sicarius Negro',
            'marca' => 'Rusty',
            'tipo' => 'Morral',
            'color' => 'Negro',
            'talles' => 'U',
            'img' => 'accesorios/morral-rusty-sicarius.jpg',
            'descripcion' => 'Este morral de cordura, con dimensiones de 18 cm de ancho, 24 cm de alto y 7 cm de profundidad, combina estilo y funcionalidad en un diseño compacto. Incluye un patch festoneado en el frente que le añade un toque distintivo.',
            'temporada' => 'Invierno, 2024',
            'precio' => 25990
        ],
    ],
];